version: "3.9"
services:
  api:
    build:
      context: ./api
    environment:
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - "5001:5001"
      - "5000:5000"
  client:
    build:
      context: ./client
    environment:
      PORT: "80"
    ports:
      - "1337:80"
