apiVersion: apps/v1
kind: Deployment
metadata:
  name: pear
spec:
  selector:
    matchLabels:
      app: pear
  template:
    metadata:
      labels:
        app: pear
    spec:
      containers:
      - name: pear
        image: ryanachten/pear-client
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

